from vst_api.indexer.Loader.SheetLoader import SheetLoader


class FoodLoader(SheetLoader):

    def __init__(
        self,
        file_path,
        sheet_name,
        data_types=None,
        skiprows=1,
        calculate_dates=False,
    ):
        super().__init__(
            file_path,
            sheet_name,
            data_types,
            skiprows=0,
            calculate_dates=calculate_dates,
        )

        self.df.rename(
            columns={
                "Bread (Lavash)": "food.bread.lavash",
                "Bread (Barbari)": "food.bread.barbari",
                "Bread (Sangak)": "food.bread.sangak",
                "Baguette": "food.baguette",
                "Cooked rice": "food.cooked_rice",
                "Cooked pasta, noodles": "food.cooked_pasta&noodles",
                "Wheat, Oats, Barley": "food.wheat&oats&barley",
                "Bean": "food.bean",
                "Chickpeas": "food.chickpeas",
                "Mung beans, lentils, dhal": "food.mung_beans&lentils&dhal",
                "Split peas": "food.split_peas",
                "Soybean": "food.soybean",
                "Cooked fava beans/Lima beans": "food.cooked_fava_beansORlima_beans",
                "Red meat (any kind)": "food.red_meat.any_kind",
                "Chicken": "food.chicken",
                "Chicken Giblets": "food.chicken_giblets",
                "Eggs": "food.eggs",
                "Fish": "food.fish",
                "Tuna (canned)": "food.tuna.canned",
                "Sausages, Kilbasa, Salami": "food.sausages&kilbasa&salami",
                "Hamburger": "food.hamburger",
                "Variety meats and by-products (heart, liver, kidney)": "food.variety_meats_and_by_products.heart&liver&kidney",
                "Brain (sheep)": "food.brain.sheep",
                "Tongue (sheep)": "food.tongue.sheep",
                "By-products (tripe, leg, trotter off, etc.)": "food.by_products.tripe&leg&trotter_off&etc.",
                "Pizza": "food.pizza",
                "Milk": "food.milk",
                "Yogurt": "food.yogurt",
                "Cheese": "food.cheese",
                "Doogh (Ayran)": "food.doogh.ayran",
                "Kashk (Whey)": "food.kashk.whey",
                "Lettuce": "food.lettuce",
                "Cabbage (Cauliflower, Broccoli,..)": "food.cabbage.cauliflower&broccoli,..",
                "Tomatos": "food.tomatos",
                "Cucumbers": "food.cucumbers",
                "Fresh leafy greens": "food.fresh_leafy_greens",
                "Cooked leafy greens": "food.cooked_leafy_greens",
                "Eggplant": "food.eggplant",
                "Celery": "food.celery",
                "Beets, Turnips": "food.beets&turnips",
                "Potatoes": "food.potatoes",
                "Carrots": "food.carrots",
                "Garlic": "food.garlic",
                "Onions": "food.onions",
                "Bell peppers": "food.bell_peppers",
                "Mushroom (cooked)": "food.mushroom.cooked",
                "Corn": "food.corn",
                "Green peas": "food.green_peas",
                "Green beans": "food.green_beans",
                "Zucchini": "food.zucchini",
                "Cantaloup melon": "food.cantaloup_melon",
                "Honeydew": "food.honeydew",
                "Watermelon": "food.watermelon",
                "Apricot": "food.apricot",
                "Sweet, Sour Cherries": "food.sweet&sour_cherries",
                "Nectarines, peaches": "food.nectarines&peaches",
                "Prunus": "food.prunus",
                "Fresh Berries (Mulberries)": "food.fresh_berries.mulberries",
                "Strawberries": "food.strawberries",
                "Plums": "food.plums",
                "Fresh Figs": "food.fresh_figs",
                "Grapes": "food.grapes",
                "Pears": "food.pears",
                "Apples": "food.apples",
                "Kiwifruit": "food.kiwifruit",
                "Citrus fruit": "food.citrus_fruit",
                "Pomegranate": "food.pomegranate",
                "Banana": "food.banana",
                "Persimmon": "food.persimmon",
                "Dates": "food.dates",
                "Fruit juice (fresh)": "food.fruit_juice.fresh",
                "Dried Fruit": "food.dried_fruit",
                "Raisins": "food.raisins",
                "Margarine (vegetable butter)": "food.margarine.vegetable_butter",
                "Butter": "food.butter",
                "Hydrogenated oils, animal fats": "food.hydrogenated_oils&animal_fats",
                "Oils": "food.oils",
                "Olive oil": "food.olive_oil",
                "Olives": "food.olives",
                "Mayonnaise, salad dressing": "food.mayonnaise&salad_dressing",
                "Walnuts": "food.walnuts",
                "Peanut": "food.peanut",
                "Other nuts (Almonds, Hindi, pistachios, hazelnuts)": "food.other_nuts.almonds&hindi&pistachios&hazelnuts",
                "seeds (pumpkin watermelon, sunflower)": "food.seeds.pumpkin_watermelon&sunflower",
                "Sugar cubes": "food.sugar_cubes",
                "Other sweets (rock candy, Noghl)": "food.other_sweets.rock_candy&noghl",
                "Honey": "food.honey",
                "Jam": "food.jam",
                "Tea": "food.tea",
                "Soda drinks": "food.soda_drinks",
                "Non-alcoholic malt beverage": "food.non_alcoholic_malt_beverage",
                "Coffee, Nescafe": "food.coffee&nescafe",
                "Ice-cream": "food.ice_cream",
                "Cookies and Sweets (dry)": "food.cookies_and_sweets.dry",
                "Cookies and Sweets (creamed)": "food.cookies_and_sweets.creamed",
                "Chocolate": "food.chocolate",
                "Chips": "food.chips",
                "Cheese Puffs": "food.cheese_puffs",
                "Halva (Tahini)": "food.halva.tahini",
                "Pickles": "food.pickles",
                "Torshi/Pickled vegetables (in vinegar)": "food.torshiOrpickled_vegetables.in_vinegar",
                "Tomato paste": "food.tomato_paste",
                "Juice (from concentrate)": "food.juice.from_concentrate",
                "Gaz (Traditional Sweet)": "food.gaz.traditional_sweet",
                "Salt": "food.salt",
                "Wheat": "food.wheat",
                "Traditional Bread": "food.traditional_bread",
                "Poultry meat (Other than chicken)": "food.poultry_meat.other_than_chicken",
                "Colostrum": "food.colostrum",
                "Traditional Greens": "food.traditional_greens",
                "Lime Juice, Verjuice, sour orange juice": "food.lime_juice&verjuice&sour_orange_juice",
                "Mango": "food.mango",
                "Baby Almonds": "food.baby_almonds",
                "Pistacia atlantica": "food.pistacia_atlantica",
                "Traditional Sweets": "food.traditional_sweets",
                "Sekanjabin": "food.sekanjabin",
                "Green peppers": "food.green_peppers",
                "Compote": "food.compote",
                "Cream, clotted cream": "food.cream&clotted_cream",
                "Sugar (white)": "food.sugar.white",
                "Crackers, wafers, biscuits": "food.crackers&wafers&biscuits",
                "Pickled vegetables (in salt water)": "food.pickled_vegetables.in_salt_water",
                "Pomegranate paste": "food.pomegranate_paste",
                "Flavored milks (chocolate-milk, fruit-milk, coffeemilk,": "food.flavored_milks.chocolate_milk&fruit_milk&coffeemilk",
                "Barley dread, diet dried bread": "food.barley_dread&diet_dried_bread",
            },
            inplace=True,
        )
